### ISSUE TITLE
Mobile is totally unusable

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/snippets.haxeflixel.com#1]
Currently, the mobile version of the site is broken - you can't see the sidebar, and, if you manage to navigate to a proof, it looks incorrectly formatted (plus, the demos don't work, because Flash)

Need to figure out how to clean it up and probably suppress the actual demo swf on mobile? Just link to the source?

**Comment by Gama11** [comment]
Switch to html5 builds for mobile? They should be able to handle something this simple, I hope...

**Comment by SeiferTim** [comment]
@Gama11 how far are we from having working HTML5 in HaxeFlixel? I've never been able to build anything for HTML5...

**Comment by Gama11** [comment]
Really? It used to work pretty well with bitfive, but it's currently incompatible and not the default on the dev branch anymore.

Mode for example seems to be running pretty well with the openfl backend right now.

**Comment by SeiferTim** [comment]
I think there are 2 problems that need to be addressed:

1: The site design itself is not setup right to work on mobile properly. The sidebar is missing, etc.  I haven't done hardly any mobile website design, so I'm not sure how to fix it, yet.

2: If we can build the demos for HTML, that would be great and solve that issue, but I don't know if everything is there yet to make it feasible.

I would like to make the site mobile friendly, so any input from more experienced mobile devs would be welcome.
