### ISSUE TITLE
Switch to HTML5?

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/snippets.haxeflixel.com#10]
Flash is dying, right? Well, at least, it seems like it _should_ be easier to use HTML5 for the demos instead of Flash... I know people use Flashblocker Extensions and things, and who knows if/when Chrome or Firefox will put out an update that totally breaks all the Flash stuff anyway... 

Let's discuss this?

**Comment by Gama11** [comment]
Why not have both? That's the plan for haxeflixel.com/demos.
