### ISSUE TITLE
Drop-down Concepts Menu

### ISSUE THREAD

**Issue by NaxeCode** [HaxeFlixel/snippets.haxeflixel.com#12]
Wondering if it'd be a good idea to make the sidebar menu drop down instead of having to go to a new page all together
![ss 2017-03-09 at 02 40 05](https://cloud.githubusercontent.com/assets/15963333/23730744/dd97081a-0471-11e7-8040-fe49dc46c9e4.png)

I was thinking it'd be kinda like the HaxeFlixel API dropdown menu but a bit more _animated_

**Comment by Gama11** [comment]
Agreed, feels weird that a new page is loaded when clicking something in the navigation.

**Comment by SeiferTim** [comment]
Switched to a more responsive accordion menu for the side bar
