### ISSUE TITLE
Recommendations: get closest and tilemap edge detection

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/snippets.haxeflixel.com#18]
From the Haxe discord: 
> i think Fabs nearest enemy and check if you're at an edge should be on the snippets page

which refer: 
- finding an object in a group that is closest to a point
- telling if an object is close to a tilemap's ledge

Both make fine additions so I'm adding this as a reminder, but we should probably have a tilemap section and a Math/FlxPoint/FlxVector section before adding these to them?

**Comment by SeiferTim** [comment]
My concern here is that these seem to be more in the 'general coding/game dev' concepts and not specific to HaxeFlixel

**Comment by Geokureli** [comment]
I agree, this seems better for a demo
